name: Toga_Armv7BinaryUpload
on:
  workflow_dispatch:
jobs:
  TogaArmv7Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }} 
    strategy:
      matrix:
        config:
          - name: Ubuntu 22.04 NDK armv7
            os: ubuntu-22.04
            compiler: armv7a-linux-androideabi19-clang++
            comp: ndk
            run_armv7_tests: true
            shell: bash {0}

    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build armv7
        if: ${{ matrix.config.run_armv7_tests }}
        run: |
            export PATH=$ANDROID_NDK_HOME:$PATH
            export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

            cd ../jni
            cp Application_v7.mk Application.mk
            ndk-build
            cd ../libs/armeabi-v7a
            cp Fruit ../../TogaII_armv7
           
      - uses: xresloader/upload-to-github-release@v1
        if: ${{ matrix.config.run_armv7_tests }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          overwrite: true
          file: "TogaII_armv7"
          update_latest_release: true
              
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.run_armv7_tests }}
        with:
          name: TogaII_armv7
          path: TogaII_armv7

