name: Toga_ArmWinBinariesUpload
on:
  workflow_dispatch:
jobs:
  SFnpsArmTest:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }} 
    strategy:
      matrix:
        config:
          - name: Ubuntu 22.04 NDK armv8
            os: ubuntu-22.04
            compiler: aarch64-linux-android21-clang++
            comp: ndk
            run_armv8_comp: false
            shell: bash {0}
            
          - name: Windows 2022 Mingw-w64 GCC x86_64
            os: windows-2022
            compiler: g++
            comp: mingw
            run_win11_comp: true
            msys_sys: mingw64
            msys_env: x86_64-gcc
            shell: msys2 {0}   

    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msys_sys }}
          install: mingw-w64-${{ matrix.config.msys_env }} make git

      - name: armv8 build
        if: ${{ matrix.config.run_armv8_comp }}
        run: |
            export PATH=$ANDROID_NDK_HOME:$PATH
            export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

            cd ../jni
            cp Application_v8.mk Application.mk
            ndk-build
            cd ../libs/arm64-v8a
            cp Fruit ../../TogaII_armv8
          
      - uses: xresloader/upload-to-github-release@v1
        if: ${{ matrix.config.run_armv8_comp }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          overwrite: true
          file: "TogaII_armv8" 
          update_latest_release: true
              
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.run_armv8_comp }}
        with:
          name: TogaII-armv8
          path: TogaII_armv8
       
      - name: win11 build
        if: ${{ matrix.config.run_win11_comp }}
        run: |
          make
          #make -j profile-build ARCH=x86-64-modern COMP=$COMP
          #make strip ARCH=x86-64-modern COMP=$COMP
          cp fruit ../TogaII_modern.exe
        
      - uses: xresloader/upload-to-github-release@v1
        if: ${{ matrix.config.run_win11_comp }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          overwrite: true
          file: "TogaII_modern.exe"
          update_latest_release: true
        
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.run_win11_comp }}
        with:
          name: TogaII_modern
          path: TogaII_modern.exe 
          
