name: Toga_Armv8BinaryUpload
on:
  workflow_dispatch:
jobs:
  TogaArmv8Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }} 
    strategy:
      matrix:
        config:
          - name: Ubuntu 22.04 NDK armv8
            os: ubuntu-22.04
            compiler: aarch64-linux-android21-clang++
            comp: ndk
            run_armv8_tests: true
            shell: bash {0}

    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build armv8
        if: ${{ matrix.config.run_armv8_tests }}
        run: |
            export PATH=$ANDROID_NDK_HOME:$PATH
            export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

            cd ../jni
            cp Application_v8.mk Application.mk
            ndk-build
            cd ../libs/arm64-v8a
            cp Fruit ../../TogaII_armv8
           
      - uses: xresloader/upload-to-github-release@v1
        if: ${{ matrix.config.run_armv8_tests }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          overwrite: true
          file: "TogaII_armv8"
          update_latest_release: true
              
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.run_armv8_tests }}
        with:
          name: TogaII_armv8
          path: TogaII_armv8
          #path: /home/runner/work/StockfishNPS/StockfishNPS/SFnps_armv8
